[package]
name = "animation_tools"
version = "0.1.0"
edition = "2021"

[features]
default = []
dbg_determinism = []
dev_mode = []


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.12.1" }
bevy-inspector-egui = "0.22"
